matrix:
  include:
  - language: java
    jdk: oraclejdk8
  - language: android
    jdk: oraclejdk8
    android:
      components:
        - tools
        - platform-tools
        - tools

        # The BuildTools version used by your project
        - build-tools-26.0.2

        # The SDK version used to compile your project
        - android-26

# Cache gradle dependencies (should be faster to download them from cache)
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# Setup environment
before_install:
  - chmod +x gradlew

script:
# Needed to prevent tests caching
  - ./gradlew clean
  - ./gradlew build
  - ./gradlew test